### ISSUE TITLE
Visual selection with '=' should auto indent

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#100]
After making a visual selection, pressing '=' should auto format that text

**Comment by guillermooo** [comment]
This interacts with the `equalprg` setting and falls back to an internal formatting function when said setting is unset. I don't think the latter is available natively in ST.

**Comment by rhelsing** [comment]
@guillermooo so is there a setting in sublime that I should enable for this to work?

**Comment by guillermooo** [comment]
@rhelsing I meant that ST lacks a built-in command for indenting a block of text; at least I don´t know about it. Therefore, it is not possible to map `=` to a default command.

**Comment by rhelsing** [comment]
@guillermooo can you think of any workarounds for this? possibly a mapping of '=' to "Reindent Lines" function in sublime on a visual selection when in normal mode?

![screen shot 2017-06-25 at 11 37 23 am](https://user-images.githubusercontent.com/392594/27518705-c42f19ca-599a-11e7-869d-df4d593e1a9e.png)

**Comment by guillermooo** [comment]
If that is available as a core command, I think it´s exactly what I was looking for. Thanks!

**Comment by guillermooo** [comment]
@rhelsing This will be available in the next version.
