### ISSUE TITLE
Can't enter normal mode after release 0.1.49

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#123]
Esc no longer enters normal mode for me. Does it work for you?

---

**How to solve this issue**

This issue is due to Package Control not deleting a file. Read the whole thread below or simply perform these steps:

1. [Locate *Data/Installed Packages*](http://docs.sublimetext.info/en/latest/basic_concepts.html#the-data-directory) on your platform
2. Delete *Six.sublime-package* if it exists

If the problem persists after that, please report it as a new issue.

**Comment by rhelsing** [comment]
@guillermooo disabled six and reenabled vintageous for the time being..

**Comment by guillermooo** [comment]
Can you please do the following:

```
import sublime
sublime.log_commands(True)
```

Then press Esc in insert mode in Six and see what gets logged?

**Comment by guillermooo** [comment]
Confirmed as working on Windows, clean ST install.

**Comment by guillermooo** [comment]
Nope, you are right. it's broken.

**Comment by rhelsing** [comment]
```
reloading plugin Six.main
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/ryanhelsing/Library/Application Support/Sublime Text 3/Packages/Six/main.py", line 5, in <module>
    from .lib import motions
ImportError: cannot import name motions
```

**Comment by guillermooo** [comment]
However, it's working in dev ok.

**Comment by guillermooo** [comment]
Thanks for that, btw!

**Comment by guillermooo** [comment]
@rhelsing Six switched to folder install (vs .sublime-package install) a few versions ago. I've just checked, and Package Control failed to remove the pre-existing Six.sublime-package file from *Data/Installed Packages*. Hopefully, deleting this file is all what you'll need to do. I've just done that in my test version and it worked (after restarting ST).

**Comment by rhelsing** [comment]
@guillermooo That did the trick! Thanks! may want to make a note for others..

**Comment by guillermooo** [comment]
Phew... Yeah, it's going to be a pain tomorrow, I guess. I'll make a release with an announcement to see if that reaches others. Thanks! Let's leave this issue open for a few days so others can check it.
