### ISSUE TITLE
Bug: window loosing focus marks buffer as dirty

### ISSUE THREAD

**Issue by eproxus** [guillermooo/Six#137]
When saving a file and changing focus to another application the buffer is marked as dirty (unsaved) again.

Using Sublime Text 3 Build 3136 and Sublime Six v0.1.54.

**Comment by guillermooo** [comment]
Thanks for the report. 

Could you please include the exact steps to reproduce this? For example, do you save in normal mode, insert mode...?

**Comment by guillermooo** [comment]
@eproxus I can't reproduce this issue. I've changed the logic that detects false dirty buffers in v0.1.55, maybe that will help.

**Comment by eproxus** [comment]
Seems to work with Sublime Text 3 Build 3139 and Sublime Six v0.1.55. I'll reopen if it crops up again.

As far as I remember, it happened when going from insert to normal mode, then switching to another application (don't know if an edit in insert mode was necessary or not).
