### ISSUE TITLE
map jj to _enter_normal_mode

### ISSUE THREAD

**Issue by manova** [guillermooo/Six#138]
One of my most useful vim hacks is mapping pressing jj to taking me to normal mode. This worked in  Vintageous. However, I'm having issues getting this to work in Six. Here is what I've tried in `Default.sublime-keymap`.
```JSON
{"keys": ["j"], "command": "vim_press_key", "args": {"key": "j"}, "context": [{"key": "vi_insert_mode_aware"}]}
```
I would like to know if there's any way to make this work. 

Thanks 🙂

**Comment by guillermooo** [comment]
This should work:

```
{"keys": ["j", "j"], "command": "vim_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "vi_insert_mode_aware"}]}
```

**Comment by manova** [comment]
Tried this and it's still not working. Any idea what could be going on?

**Comment by guillermooo** [comment]
```
{ "keys": ["j", "j"], "command": "vim_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "vi_insert_mode_aware"}]},
```

@manova I use this one too, and the above is working fine for me. You should make sure that you don't have any Vintageous custom key bindings.

**Comment by manova** [comment]
@guillermooo I figured out the issue. Instead of adding your suggested line to `/Users/okoh/Library/Application Support/Sublime Text 3/Packages/Six/Default.sublime-keymap` add it to `/Users/okoh/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings`. To be safe, I also deleted the previous entry I had in there in order to make the hack work for Vintageous which looks as follows `{ "keys": ["j", "j"], "command": "_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}] }. So, as you pointed out, the line to add to sublime's key map file is
```JSON
{ "keys": ["j", "j"], "command": "vim_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "vi_insert_mode_aware"}]},
```
Thanks for your help 🙂
