### ISSUE TITLE
Implement :s (ie :s/find/replace/g)

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#139]
- find/replace operator
- with g option for all on line
- line by line of a visual selection

**Comment by Mattiaslndstrm** [comment]
I'm also voting for this!

**Comment by jwkicklighter** [comment]
With % for entire file.

**Comment by rhelsing** [comment]
@guillermooo any plans for this in the near future? This is just about the only thing I run into on a regular basis

**Comment by guillermooo** [comment]
@rhelsing I'll try to sort out a couple things first and then I'll look into adding this one. (I'll be away starting Nov 4th for a week, so I'll be able to plan and design, but probably not do much coding during that time.)

**Comment by guillermooo** [comment]
Already in the newest version (basic implementation). I'll add features gradually, but I'll close this issue now. You can report missing `:s` features in separate issues.
