### ISSUE TITLE
Bind jj to enter normal mode not working

### ISSUE THREAD

**Issue by GeordieP** [guillermooo/Six#152]
I've had this issue for a while. I've read through #138, and tried the key bind line copied from both it and from the official docs page.

Here's a video of setup on a fresh install. Only other package installed is package control.
https://www.youtube.com/watch?v=s790U_MNUhM

I've had this happen on both Windows and Linux, on more than one machine each. I see nothing of interest printed in the Sublime console on startup.

 I can't help but feel like I'm doing something wrong at this point, as it appears to work for others.

**Comment by guillermooo** [comment]
Thanks for the detailed report @GeordieP !

Here's the key binding copied straight from my personal `.sublime-keymap`:

```
{ "keys": ["j", "j"], "command": "six_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "six_is_in_insert_mode"}]},
```

Some context names have changed recently. I need to document this...

**Comment by GeordieP** [comment]
Fantastic, that line works perfectly.
Thank you, and thanks for all your hard work on Six. Progress has been moving very quickly, and it's shaping up to be the best ST Vim plugin.

**Comment by dannycodes** [comment]
Thanks Guillermooo!
