### ISSUE TITLE
Ctrl-w + h,j,k,l for switching between panes

### ISSUE THREAD

**Issue by EduardoBautista** [guillermooo/Six#155]
This is a command I use all the time that is available in Vintage mode.

**Comment by guillermooo** [comment]
<kbd>Ctrl-w</kbd>-<kbd>h</kbd> and <kbd>Ctrl-w</kbd>-<kbd>l</kbd> should work today in Six, but first you need to set `enable_ctrl_keys` to `True` in *Packages/User/Six.sublime-settings*. There's an item in the command palette called *Preferences: Six Settings* that should open that file.

**Comment by guillermooo** [comment]
The others will be added later.

**Comment by EduardoBautista** [comment]
@guillermooo I don't have the _Packages/User/Six.sublime-settings_ file listed in the command palette.

**Comment by guillermooo** [comment]
![cp](https://user-images.githubusercontent.com/684948/28733917-a961376e-73de-11e7-9e4d-dc2a48aea52f.png)

@EduardoBautista This is what you should get.

**Comment by EduardoBautista** [comment]
Ah yes, sorry.  It showed up after an update.  Thanks!

**Comment by guillermooo** [comment]
De nada ;)
