### ISSUE TITLE
Ctrl-r not working right now

### ISSUE THREAD

**Issue by circlecrystal** [guillermooo/Six#159]
I have already set "enable_ctrl_keys": true in setting file, yet ctrl-r doesn`t work properly.

**Comment by guillermooo** [comment]
Just checked and `cwfoo<Esc>u<C-r>` worked for me. Any specific repro steps?

**Comment by guillermooo** [comment]
@circlecrystal I'm closing this one as I cannot reproduce it. Please reopen if the issue persists for you.
