### ISSUE TITLE
feature request: center the viewport when highlighting searches

### ISSUE THREAD

**Issue by anthrotype** [guillermooo/Six#160]
... so that the currently highlighted search (when using `/`, `?`, `*`, or `&`, as well as `n` and `N`) is is at the center of the screen, like pressing 'zz'.

this would make it more visible, I think.

**Comment by guillermooo** [comment]
ST does not do this natively either if the occurrence is in the visible area. As soon as the occurrence it is outside the visible area, Six does center the hit on the screen, as does ST.

Six should use the same highlighting for search occurrences as ST, but unfortunately it isn't exposed.

**Comment by guillermooo** [comment]
I see what you mean now. Yes, I think that can be changed to work as you suggest.

**Comment by anthrotype** [comment]
Thank you!

**Comment by guillermooo** [comment]
This will be implemented in the next build.

**Comment by anthrotype** [comment]
it works great, thanks! 👍
