### ISSUE TITLE
yank line (yy) shouldn't include last \n

### ISSUE THREAD

**Issue by yeled** [guillermooo/Six#162]
AFAIK `yy` in vim does not yank the `\n` as well. Should we replicate this detail?

**Comment by guillermooo** [comment]
Maybe this depends on config, but I get this in Vim (Windows):

Buffer:

```
1 aaa
2 bbb
3 ccc
```

Caret anywhere on line 2.

```
yy
:reg
# bbb^J
```

Contrast this with:

```
yw
:reg
# bbb
```

I think Six is doing the right thing, but let me know if I'm missing somehing.

**Comment by yeled** [comment]
damn you are right. I should have checked 👎
