### ISSUE TITLE
Add-ons such as surround or targets?

### ISSUE THREAD

**Issue by eproxus** [guillermooo/Six#167]
Some of my favorite Vim plug-ins are [vim-surround](https://github.com/tpope/vim-surround) and [targets.vim](https://github.com/wellle/targets.vim#argument-text-objects). Vintageous had a basic implementation of vim-surround.

Is it possible to write add-ons or plug-ins for Six? If so, how would one go about it?

**Comment by guillermooo** [comment]
Technically, I think it's already possible, but the APIs are not stable. I'll try to give this some more thought in the coming weeks.

**Comment by eproxus** [comment]
Thanks, let me know how it goes 😄

**Comment by jwkicklighter** [comment]
If there was support for this (and proper find/replace using :s/word/replacement/g), I would probably buy both Sublime and Six. Not sure if I'm the only one in that boat, but good vim support is keeping me in VSCode right now.

**Comment by rhelsing** [comment]
@jwkicklighter see issue #139

**Comment by guillermooo** [comment]
Cmdline commands are not really planned for this version, but I keep including some by popular demand. I am also missing `:s`, for example, so a simplified version of it may be available sooner than planned.

As for custom plugins, I'll try to look into this again (I've been away for a while), but my priority is fixing bugs in normal, operator pending, visual[ line] mode and ensuring that most people don't miss any important commands in those modes.

**Comment by guillermooo** [comment]
@eproxus FYI - https://github.com/SublimeSix/plugin-surround
