### ISSUE TITLE
Please add support for skipping paragraphs with the curly brace keys

### ISSUE THREAD

**Issue by axel22** [guillermooo/Six#168]
I just switched from Vintageous to Sublime Six, and I noticed that:

```
} 
Jump forward one paragraph.
{ 
Jump backward one paragraph.:
```

don't work.

I had to install the Sublime Text "Move By Paragraph" plugin to move around using `{` and `}`, but this does not work in visual mode - my selection is lost when moving around.

**Comment by guillermooo** [comment]
Duplicate of #164
