### ISSUE TITLE
Implement =

### ISSUE THREAD

**Issue by eproxus** [guillermooo/Six#170]
Sublime has the _Indentation: Reindent Lines_ command in the Command Palette, perhaps this could be used?

**Comment by guillermooo** [comment]
This should be available today. I will double check.

**Comment by eproxus** [comment]
It could be that it registers as a command because I see the `=` character in the bottom bar. It doesn't have any effect though.

**Comment by guillermooo** [comment]
`=<motion>` seems to be implemented. Closing this.
