### ISSUE TITLE
Implement tab switching with `gt` and `gT`

### ISSUE THREAD

**Issue by brianpmaher** [guillermooo/Six#174]
Title says it all.  I'd like to be able to switch tabs with `gt` and `gT` as I would in vim.

**Comment by michaelkoper** [comment]
If you want this right now. I solved this with adding these lines in my keymap file: 

    { "keys": ["g", "t"], "command": "next_view", "context": [
      { "key": "setting.command_mode", "operand": true },
      { "key": "setting.is_widget", "operand": false }
    ]},
    { "keys": ["g", "T"], "command": "prev_view", "context": [
      { "key": "setting.command_mode", "operand": true },
      { "key": "setting.is_widget", "operand": false }
    ]},

**Comment by guillermooo** [comment]
Implemented.
