### ISSUE TITLE
Macros dissappear when restarting Sublime

### ISSUE THREAD

**Issue by Mattiaslndstrm** [guillermooo/Six#177]
As title says.

**Comment by Mattiaslndstrm** [comment]
Any plan on implementing this? I use macros quite a bit, and it's frustrating to recreate them every time I restart Sublime.

Thank you!

**Comment by guillermooo** [comment]
AFAIK Vim only keeps macros around if you explicitly issue a `:mksession` command at some point. Currently Six has no notion of config persistence beyond plain Sublime Text settings. I think this is a high priority item, but I'm not sure how Six should implement it right now.

In fact, my plan is to enable first key remappings in some modes in the near future. That will require some infrastructure to support config persistence via a session file or something of that sort (I'm actually considering an SQLite db as first choice).

In other news, I'm about to enter a long cycle of bug fixing and refactoring (big changes to internal APIs) and I expect to add very few new features in the coming weeks, but I'll have a think about this one. This is just a rough plan, but when I'm done with this cycle, I also hope the whole testing/building/deployment pipeline will be much improved (not that it's very complex, but now it's completely manual) and I'll be able to focus more on code again.

**Comment by Mattiaslndstrm** [comment]
Thank you for a detailed answer! It makes me glad that you are in for the long term. This is a great plugin.

**Comment by guillermooo** [comment]
@Mattiaslndstrm It's a bit rough around the edges, but if you want to persist macros today, you can put the following in your `User/sixrc.py` file.

Reference: https://github.com/SublimeSix/sample-sixrc

```python
from Six.lib.macros import macro_registers
# Use lists of pre-parsed Vim key notation tokens.
macro_registers["q"] = list("ihello, world! ") + ["<Esc>"] + list("BB12~")
```

**Comment by guillermooo** [comment]
@Mattiaslndstrm Well, the above won't really work until I release the current dev build! 😉

**Comment by guillermooo** [comment]
@Mattiaslndstrm This should be working in the latest dev build.

**Comment by Mattiaslndstrm** [comment]
Thank you @guillermooo! It looks easy enough. I will try this during the weekend!
