### ISSUE TITLE
Can't bind `space` for commands

### ISSUE THREAD

**Issue by dvcrn** [guillermooo/Six#178]
Example: 

```
{ "keys": ["space", "p", "f"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true}, "context": [{"key": "six_is_in_command_mode"}]}
```

Hitting `space`, `p` results in `paste` being executed

```
{ "keys": ["escape", "p", "f"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true}, "context": [{"key": "six_is_in_command_mode"}]}
```

works fine on the other hand. I am using `space` as my custom leader and would like to bind commands on keybindings starting with it

**Comment by guillermooo** [comment]
Even though custom mappings are not yet officially supported, have you tried `" "` instead of `space`?

**Comment by dvcrn** [comment]
That seemed to work! Odd. According to [this](http://docs.sublimetext.info/en/latest/reference/key_bindings.html#bindable-keys), `space` should have done the job too.
