### ISSUE TITLE
Sublime CMD+D select should behave as visual

### ISSUE THREAD

**Issue by dvcrn** [guillermooo/Six#179]
When using sublime texts build in command to select blocks of text, Six should treat it the same as visual mode. For example (`_` is cursor position):
```
_hoge hoge hoge
```

CMD+D selects `hoge`, but now using a motion like `c` is not doing anything. Using `ve` on the other hand is also selecting `hoge` but with full support for motions like `c`. 

This is important because multiple word selections for example with multiple cursors can't use motions like `c` to quickly replace all selected words

**Comment by Mattiaslndstrm** [comment]
See #169 as well

**Comment by guillermooo** [comment]
The preferred way to create multiple selections from normal mode can be found in the post linked by @Mattiaslndstrm.

`Ctrl/Cmd+D`, however, seems to be a legitimate operation in Sublime Text. That said, the interaction with other modes could be improved. Perhaps a sequence like `Ctrl+D, <Esc>` should switch to visual mode, or, as you suggest, `Ctrl+D` should directly switch to visual mode (but to reiterate, I think using multiple sels in insert mode is probably a good idea in Six).

**Comment by DrBones** [comment]
The `gh` command is a good substitute for `Ctr/Cmd -d` but there is a multitude of selection options in SublimeText (like expand to scope or tag, which is really handy) and plugins that select stuff (like Expand Region, which is even more handy) also do not know about visual mode.

I support that all the normal selection command of SublimeText should directly switch to visual mode so one does not have to type `gh` which makes such operations a little clunky and feels unnecessary

Maybe as a default=off option that users that like to use both SublimeText and vim in cooperation can set if they want.

**Comment by guillermooo** [comment]
I will investigate switching to visual mode automatically after the `expand_selection` command.

**Comment by guillermooo** [comment]
@DrBones The way I see this working is as follows:

1. User enters insert mode
2. User selects some text through CMD+d, CMD+M, etc... 
3. Now non-empty selections exist in the buffer in insert mode
4. User presses Esc to abandon insert mode
5. Six switches to visual mode (not normal mode), as there are non-empty selections in the buffer

This seems to work well in my limited testing, but it introduces a special case for Esc. I think I'll give this feature a try and see if it should be configurable.

**Comment by guillermooo** [comment]
Implemented. Pre-existing selections in insert mode will not be collapsed when switching back to Normal mode. Instead, Six will switch straight to Visual mode.
