### ISSUE TITLE
Auto insert line break

### ISSUE THREAD

**Issue by math2001** [guillermooo/Six#180]
I'm pretty sure it's the `textwidth` option on vim that enables this (when different than 0).

**Comment by guillermooo** [comment]
Interesting. First time I hear about it. Is suppose this is mainly useful when pasting?

**Comment by math2001** [comment]
> Is suppose this is mainly useful when pasting?

It probably is pretty useful for pasting (although I'm not even sure it actually gets activated when we paste), but no, it's just when you type markdown for example, you don't have to worry about the ruler, it automatically inserts line break *before* the word that *crosses* the ruler:

Have a look at this:

![vim-textwidth](https://user-images.githubusercontent.com/15224242/30516285-e57ddeb6-9b7d-11e7-8014-a9bcabd2f18a.gif)

I never it enter (except to get out of command mode, of course).

**Comment by guillermooo** [comment]
That looks really useful, but I don't think ST supports anything like that out of the box. I think Six will have to listen on every buffer change event and go from there.

**Comment by math2001** [comment]
I'm closing this issue as I think it could (maybe even should) be implemented in a separated plugin and the number of issue 😄 . I might do it in the future.

**Comment by math2001** [comment]
Quickly made a plugin to do that over here: https://github.com/math2001/textwidth

**Comment by babygau** [comment]
Tks for sharing 👍
