### ISSUE TITLE
Shift+[ / Shift+] jumps not working in visual mode

### ISSUE THREAD

**Issue by dvcrn** [guillermooo/Six#181]
When entering visual mode, Shift+[ and Shift+] seem to no longer be able to jump blocks. As soon as visual mode is left, everything works fine again

**Comment by guillermooo** [comment]
If you are referring to the [paragraph motion](http://vimdoc.sourceforge.net/htmldoc/motion.html#{), it seems to be working now. Closing this issue based on that.
