### ISSUE TITLE
`J` swallows first word if preceded by \t

### ISSUE THREAD

**Issue by yeled** [guillermooo/Six#182]
Watch this gif to see what I mean.

http://spodder-com-photo.s3.amazonaws.com/screenshots/2017-09-22%2009.14.34.gif

I am pressing `J` to remove the `\n`

**Comment by guillermooo** [comment]
Also happens if there's a single space before the first word in the next line.

```
aaa
 bbb
ccc
```

`J` from first line swallows `bbb`.

**Comment by guillermooo** [comment]
Should be fixed in the next build.
