### ISSUE TITLE
yanking text does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#183]
I tried `y` one some text and I also tried `yi"` to tank inside quotes and more and neither of them worked. 😞

**Comment by babygau** [comment]
@nikitavoloboev I got no issue here. Have you tried 

`Cmd+Shift+P` -> Preferences: Six Setting

```
{
  "use_system_clipboard": true
}
```

**Comment by nikitavoloboev** [comment]
That fixed it, Thank you @babygau
