### ISSUE TITLE
How to set leader key?

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#185]
I want to set leader key as space. And I want to map <leader> + w to save on file. 

Is this possible to do that?

**Comment by babygau** [comment]
Yes, you can do it, that's what I'm doing with my keybinding.

```
[
  // Other keybinding....

  // Unbind `space` in `normal-mode`
  // in order to make it a `prefix` keybinding
  { "keys": [" "], "command": "noop", "context": [{ "key": "six_is_in_command_mode" }] },

  // `SPC w` to save
  { "keys": [" ", "w"], "command": "save", "context": [{ "key": "six_is_in_command_mode" }], 
  "description": "save file/buffer" }
]
```

**Comment by nikitavoloboev** [comment]
Hi @babygau 

Can you please help, I tried using this config [here](https://github.com/nikitavoloboev/dotfiles/blob/master/sublime/preferences.sublime-settings#L32) but it fails for me. 😞

**Comment by babygau** [comment]
@nikitavoloboev 
That file is **User Setting** not **Keybinding**

Choose `Sublime Text -> Preferences -> Keybinding` and put the above snippet.

**Comment by nikitavoloboev** [comment]
This works. Thank you.

**Comment by guillermooo** [comment]
@babygau  @nikitavoloboev 

I like the leader key trick! But keep in mind you want Six to process spaces for `f`, `t` and other motions/operand accepting input.

Follow the pattern [here](https://github.com/guillermooo/Six/issues/199#issuecomment-372550919) to do that.
