### ISSUE TITLE
Bug with gqap on last paragraph

### ISSUE THREAD

**Issue by math2001** [guillermooo/Six#190]
When I run `gqap` on the last paragraph, it creates 2 cursors, one on the last paragraph, and one on the previous one.

**Comment by guillermooo** [comment]
The extra selection is created after calling the `wrap_lines` ST built-in command. I have tested this in plain ST and it doesn't happen. I have not tested this in plain ST after enabling `command_mode` and adding a wide selection.

I've added a workaround that counts the number of selections before and after calling `wrap_lines` and adjusts them as needed.
