### ISSUE TITLE
Indentation issue with the repeat command (.) when selecting from the bottom to the top

### ISSUE THREAD

**Issue by scebotari66** [guillermooo/Six#191]
Given the following code:
```
    function() {
            var a = getA();
            var b = getB();

        return a + b;
    }
```
In visual mode, with the cursor located at the declaration of the `b` variable, execute the following commands:
```
V
k
<
.
```
![repeat_indenting_issue](https://user-images.githubusercontent.com/329976/32315492-f86be8c8-bfb4-11e7-94c7-0a4a2524f6be.gif)

When executing the `.` repeat command, the indentation of the `var a` and `var b` lines is expected, instead, the  `var a` and the `function()` lines get indented. 

The indentation works as expected when beginning the selection from the top (the `var a` line) though.

**Comment by guillermooo** [comment]
Status:

- [ ] Fixed for Visual Mode
- [ ] Fixed for Visual Line Mode
