### ISSUE TITLE
implement gj/gk in visual mode

### ISSUE THREAD

**Issue by DrBones** [guillermooo/Six#192]
They are disabled at the moment. I feel greedy for requesting them but since gj/gk work now in normal mode (albeit with a workaround) I hope it might not be too much work to implement them with the same work around in other modes as well.

Realted but OT: I tried mapping j->gj only in normal mode so I could use the line wise behaviour in visual mode but "six_is_in_command_mode" is apparently true for visual mode and I could not find a proper context. I know key rebinding is not supported atm...but what would the unsupported way be ? :)

Thanks

**Comment by guillermooo** [comment]
Will be implemented in the next dev build.
