### ISSUE TITLE
I can't find a Donate link anywhere here or sublimesix.com

### ISSUE THREAD

**Issue by michaelkoper** [guillermooo/Six#194]
I love this plugin and don't want it to go away.  I would like to pay a little bit more than the price of the license. 

Is there an easy way to do this?

**Comment by guillermooo** [comment]
Thanks @michaelkoper !

I use Six every day and I've been making Vim plugins for ST for years. (I sure hope this is the last one!) All this to say it's unlikely that I will abandon Six any time soon.

However, if you feel like paying more and have no use for additional licenses (send me the names + email addresses if you do!), this is my PayPal.Me: https://www.paypal.me/guillermooo

**Comment by michaelkoper** [comment]
Glad it isn't going away any time soon :) Sent you some to your paypal account!

Thank you @guillermooo!
