### ISSUE TITLE
How to add case insensitive search

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#195]
In vim I could do `:set ignorecase` but I am not sure how to do it here.

Thank you for any help.

**Comment by guillermooo** [comment]
In the future it will be possible to do that. However, the feature is not ready yet.

In the meantime, you can use the Six settings file and add this:

```json
{
	"enable_ignore_case": true
}
```

To open the settings file, select _Preferences: Six Settings_ from the command palette (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>).

**Comment by guillermooo** [comment]
@nikitavoloboev Feel free to reopen if the info above didn't work for you.
