### ISSUE TITLE
Can't go to line when in visual line mode

### ISSUE THREAD

**Issue by EduardoBautista** [guillermooo/Six#197]
Say I go into visual line mode (shift + v).  I then want to go to line 55 so I type `55gg` or `55G` but that doesn't seem to work.

**Comment by guillermooo** [comment]
Not implemented yet. I'm about to start a long refactoring cycle, but I'll try to squeeze this one in.

**Comment by guillermooo** [comment]
@EduardoBautista A typo was causing an error. Will fix for the next dev build.
