### ISSUE TITLE
How to make save + close command mapping 

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#199]
I tried to do this: 

```json
    {
    "keys": [" ", "a"],
    "command": "save",
    "command": "close",
    "context": [{ "key": "six_is_in_command_mode" }]
  },
```

But that does not combine the commands. I am not sure how I can combine them if I can. Thank you for any help.

**Comment by guillermooo** [comment]
I don't think that will work. While you are using Six and are in normal/visual mode, key presses go through the Six key handling mechanism. You cannot execute native ST commands directly this (at least I don't think you can) and there's limited things you can do even following the Six patterns for json-based key bindings. I want to work on key mappings, but sorting out other priority items slowed me down.

Just to understand your intention better, is `:wq` not enough for your use case? For example, I've mapped `<space>` to be `:`, so I can do `<space>wq` and the active file is saved and closed. Actually, I do that compulsively.

**Comment by guillermooo** [comment]
These are the current custom key bindings I'm using myself:

```json
{ "keys": ["j", "j"], "command": "six_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "six_is_in_insert_mode"}]},
{ "keys": [" "], "command": "six_press_key", "args": {"key": ":"}, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]}
```

**Comment by nikitavoloboev** [comment]
`:wq` is what I want to achieve. I just thought I had to do it this way by triggering two commands.

**Comment by nikitavoloboev** [comment]
Hey @guillermooo 

This doesn't seem to work for me for some reason. The `j j` one does but not `space + :`.

I also tried this:
`{ "keys": [" "], "command": "six_press_key", "args": {"key": "a"}, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]},
`

**Comment by guillermooo** [comment]
If you add the key bindings I showed above, you should do `<space>wq` (or any other ex command available). But you should drop the `:`. Does that help?

**Comment by nikitavoloboev** [comment]
Still confused. I don't see where in your command it triggers `:wq` (save & close). I have this now:
` { "keys": [" ", "a"], "command": "six_press_key", "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]},
`

**Comment by nikitavoloboev** [comment]
To clarify I want `<space>:` to trigger `:wq`.

**Comment by guillermooo** [comment]
OK, I'm not making myself clear. I'll try again!

What I'm showing you is how to enter ex mode using the `<space>` key, not how to make `<space>a` save and close.

I use the `<space>` key to enter ex mode (normally activated via `:`) and *then* I type in `wq`. So after adding the key binding above, every time I want to close and save the active file, I press `<space>wq<enter>`; but I press the whole sequence myself. For me this works fine; it's quick and convenient enough.

If you still have questions, let's try to answer them here or email me for details!

**Comment by guillermooo** [comment]
@nikitavoloboev So `<space>wq<enter>` is not good enough for your use case?

**Comment by nikitavoloboev** [comment]
Yes it's not. I also currently use <space>wq but I use that operation very often and want to bind it to just <space>a. Thank you.

**Comment by nikitavoloboev** [comment]
My current Six config:
```json
  {
    "keys": [" "],
    "command": "noop",
    "context": [{ "key": "six_is_in_command_mode" }]
  },
  {
    "keys": [" ", "w"],
    "command": "save",
    "context": [{ "key": "six_is_in_command_mode" }]
  },

  { "keys": ["j", "j"], "command": "six_press_key", "args": {"key": "<Esc>"}, "context": [{"key": "six_is_in_insert_mode"}]},
 { "keys": [" ", "a"], "command": "six_press_key", "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]},
  {
    "keys": [" ", "q"],
    "command": "close",
    "context": [{ "key": "six_is_in_command_mode" }]
  }

```

**Comment by guillermooo** [comment]
I'm not sure this will play well with all Six pending states, but you can try:

```
{ "keys": [" ", "a"], "command": "six_press_key", "args": {"key": [":", "w", "q", "<CR>", "<Esc>"], "is_interactive": false }, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]}
```

This is kind of unsupported, but it should work reasonably well.

**Comment by nikitavoloboev** [comment]
This works really close to what I want. However I realised that what I actually need is `Save` and then `Close` and not `:wq`. The reason is that `:wq` leaves off the window open like so:

![2018-03-11 at 22 41](https://user-images.githubusercontent.com/6391776/37258803-6ae4d26a-257d-11e8-8449-2e862fca3055.png)
 
But `Close` closes the window. Can you rewrite this action to avoid this please. Thank you very much. I really appreciate it.

**Comment by guillermooo** [comment]
I see. So you want to replicate the Vim behavior where closing the last open buffer closes the window too. I'll try to implement that in the next build.

**Comment by nikitavoloboev** [comment]
That would be super nice. Thank you.

**Comment by guillermooo** [comment]
@nikitavoloboev From 0.8.81 you should switch from

```
{ "keys": [" ", "a"], "command": "six_press_key", "args": {"key": [":", "w", "q", "<CR>", "<Esc>"], "is_interactive": false }, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]}
```

to

```
{ "keys": [" ", "a"], "command": "six_press_key", "args": {"key": [":", "w", "q", "<CR>"], "is_interactive": false }, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]}
```

(Remove trailing `<Esc>` key.)

**Comment by nikitavoloboev** [comment]
Thank you @guillermooo 

Your update works wonderfully so as the mapping.

**Comment by nikitavoloboev** [comment]
Hi @guillermooo 

There is a big issue with how `:wq` now. It actually quits Sublime Text for me when I `:wq` (cmd + q) and not just close the window (cmd + shift + w).

Can you please make it trigger cmd + shift + w instead. Thank you.

**Comment by guillermooo** [comment]
Oops. Will fix asap.

**Comment by guillermooo** [comment]
@nikitavoloboev Should be fixed by 0.8.82. Feel free to reopen if it's not the case.

**Comment by eproxus** [comment]
@guillermooo With v0.8.88 I get the following error when trying your latest example from above:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1066, in run_
    return self.run(edit, **args)
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\commands\press_key.py", line 96, in run
  File "C:\Users\guillermo\Utilities\Sublime Text 3\Data\Packages\Six\commands\press_key.py", line 60, in resolve
TypeError: sequence item 0: expected str instance, list found
```
Did something change?

**Comment by guillermooo** [comment]
@eproxus 

Vim mappings in normal mode have been introduced. You should now be able to map keys for normal mode (not visual mode or any other mode yet) using `:nmap`. For example, the above mapping would translate to:

```
:nmap <Space>a :wq<CR><Esc>
```


An it seems that I've changed to the `six_press_key` to reject `list<str>`. I will see if I can fix that.

For how to persist the above command between sessions, please refer to the 0.8.88 changelog.

**Comment by guillermooo** [comment]
@eproxus Should be fixed by 0.8.89 (out right now).

**Comment by nikitavoloboev** [comment]
Hey @guillermooo. With new update this mapping:
```json
 { "keys": [" ", "a"], "command": "six_press_key", "args": {"key": [":", "w", "q", "<CR>"], "is_interactive": false }, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]},
```
Stopped closing the window when closing the last open tab. Is it possible to change it so it does?

Thank you.

**Comment by guillermooo** [comment]
I will change the handler so that if after exiting Ex mode the window has 0 views (or 1 transient view), ST will quit.

**Comment by guillermooo** [comment]
Should be fixed in the next build.

**Comment by eproxus** [comment]
@guillermooo Sounds great. Where do I add that mapping? Can't find anything in the documentation about an RC file...

Actually, what I'm trying to do is to map leader key commands to Sublime commands:

```json
    { "keys": [",", "d"], "command": "goto_definition", "context": [{ "key": "six_is_in_command_mode" }] },
    { "keys": [",", "r"], "command": "goto_reference", "context": [{ "key": "six_is_in_command_mode" }] },
```

These seem to work, but it breaks leader key usage in other scenarios (like `f,` for example).
