### ISSUE TITLE
Escape key: prevented from hiding panels

### ISSUE THREAD

**Issue by math2001** [guillermooo/Six#2]
Hello!

The escape key is prevented from hiding panels, even when I'm in command mode...

Thanks anyway for this package! 👍

**Comment by guillermooo** [comment]
As a temporary solution, you can use the key to toggle the console to dismiss panels.

What about the console; should it be dismissed by <key>Esc</key> too?

**Comment by math2001** [comment]
> What about the console; should it be dismissed by Esc too?

Yep. when in command mode, the esc key should do what it would do if this package was disabled (IMO).

**Comment by guillermooo** [comment]
BTW, this is fixed in the latest pre-release.
