### ISSUE TITLE
esc, c, tab in command mode crashes Sublime

### ISSUE THREAD

**Issue by Mattiaslndstrm** [guillermooo/Six#201]
There might be other combinations as well, but the problem seems to be tab in command mode. While I can't be fully sure this is due to Six, it seems very likely.

**Comment by guillermooo** [comment]
@Mattiaslndstrm Six currently ignores the `Tab` key. I'll try to fix that in the next dev build. However, the sequence `Esc, c, Tab` in normal mode does not crash Six for me. It simply causes Six to stay in operator pending mode for `c`.

**Comment by guillermooo** [comment]
`<Tab>` should now be enabled in the  latest dev build.
