### ISSUE TITLE
o is adding a tab

### ISSUE THREAD

**Issue by Mattiaslndstrm** [guillermooo/Six#204]
Under certain circumstances o is adding a tab when there should be none. So far I have only noticed in Python. This might be a bug with the Python language implementation in Sublime.

`t = (1, 2, 3)`  + `o`

leads to:

```
t = (1, 2, 3)
    I
```

Where I is the cursor.

**Comment by guillermooo** [comment]
I see this fairly often in other languages too. When you press `o`, Six calls a default Sublime Text macro, so the problem in principle should lie with Sublime Text's indentation rules.

**Comment by guillermooo** [comment]
@Mattiaslndstrm Six now removes automatic indentation after `o<Esc>`. I'll close this issue. Let me know if that isn't what you meant.
