### ISSUE TITLE
Window focus change reverts to normal mode

### ISSUE THREAD

**Issue by slice** [guillermooo/Six#207]
When changing the focus of the Sublime Text (switching to another space, opening a window, etc.) while in insert mode, Six reverts to normal mode when switching back to Sublime.

I like to switch between windows frequently while programming, especially if I am looking at code or documentation to reference, so it would be nice if the current input mode could be retained between focus changes.

**Comment by guillermooo** [comment]
#205

**Comment by guillermooo** [comment]
@slice I do that also often, but I can't repro the bug. Do you know which version of Six you are using? Could you provide specific repro steps?

**Comment by guillermooo** [comment]
Nevermind, I can see it now.

**Comment by guillermooo** [comment]
I'll close this one in favor of #205, since that one was reported first.
