### ISSUE TITLE
Start-up sequence is too slow

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/Six#208]
#205

**Comment by guillermooo** [comment]
@nikitavolovoeb Actual start-up time for Six is ~0.25s for me most of the time. Total start-up time (from starting ST to being able to type in normal mode) is in the 2-3s range. There's a massive difference for me between using a couple of additional packages or none except Six.  In the second case, total start-up time goes down to ~1s.

I'm seeing slowdowns in macOS at start-up when opening Markdown files from the command line. Not so in Windows. I am still not sure what the issue is.

In the next dev build, Six will log its start-up time (Six package loading). That excludes the load time of packages loaded before Six. If your Six start-time isn't too high, try disabling other packages and check if Six responds quicker.

**Comment by guillermooo** [comment]
@nikitavoloboev In the latest dev build, you should see something like the following in your ST console:

![image](https://user-images.githubusercontent.com/684948/41823385-601ba9a6-77ff-11e8-8831-58de719b45ee.png)

That will tell you how long it took Six to fully load. As I mentioned before, that doesn't include the total ST start-up time. If you see an abnormally large number there, maybe Six is at fault. Otherwise, other plugins you have installed may be causing a delay in the loading of Six. Ideally, Six should be loaded before any other package, but I don't think that's possible.

**Comment by nikitavoloboev** [comment]
Hi @guillermooo, I think I realized now why the startup time was at times super long for me.

You have changed something and now on macOS, the cmd + shift + w hotkey that should **close the window**. Occasionally quits the entire app.

Can you please take a look at this and hopefully replicate/fix this issue. Thank you very much.

**Comment by nikitavoloboev** [comment]
For example this binding: 

```json
  {
    "keys": [" ", "q"],
    "command": "close",
    "context": [{ "key": "six_is_in_command_mode" }]
  }
```

Works perfectly well for me. It closes the window if I run space + q on last file in window. I want `:wq` do the same, not sure why it doesn't.

**Comment by guillermooo** [comment]
@nikitavoloboev Got it. It's this macOS-only thing with windowless apps. I think `:wq` calls `hot_exit`, which probably fully terminates the app on all OSes. That also explains why you thought the change is recent; it's actually the case (before it used to be `close` or `exit`; I need to check which one is the actual good one).

**Comment by guillermooo** [comment]
This issue should be fixed in the latest dev versions.
