### ISSUE TITLE
ciw is not working if there is no newline present

### ISSUE THREAD

**Issue by Mattiaslndstrm** [guillermooo/Six#209]
ciw is not working on the last line of the file. It only ends up deleting the characters between the cursor and the end of the file:

`word` + `ciw` = `wor`if the cursor is positioned at the `d`

**Comment by guillermooo** [comment]
@Mattiaslndstrm Can't reproduce this one. Maybe it's been fixed in the meantime? Closing. Please reopen if you are still having the same issue.

**Comment by Mattiaslndstrm** [comment]
I can't reopen, but the issue is still present. If you place the cursor on the last word of the last line it still just deletes the final character.

**Comment by guillermooo** [comment]
Found it. Thanks for the report. Will be fixed in the next dev version.
