### ISSUE TITLE
implement f support

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#21]
In normal mode, I should be able to press f , and the cursor should move to the next ,

**Comment by guillermooo** [comment]
When `f` is expecting input, Six will accept any character. Nothing special should need to be done in order for `,` to be accepted as input. I've just double checked and it's working fine for me as far as I can tell. Maybe you have some custom key binding defined for `,`?

**Comment by rhelsing** [comment]
@guillermooo hmm.. I only have two other key bindings and neither involve `f` or `,` :

I tried restarting, still no dice. My sublime build is 3126

```
[
  { "keys": ["super+\\"], "command": "toggle_side_bar" },
  { "keys": ["super+down"], "command": "select_lines {\"forward\": true}" },
]
```

**Comment by guillermooo** [comment]
Here's what I do:

1. Create new buffer with contents: `aaa bbb, ccc`.
2. Place caret at 0 position (BOF).
3. Type <kbd>f</kbd>, <kbd>,</kbd> in normal mode.

The caret advances to position 7 as expected.

Tests also check this and are passing. Maybe we're talking about different things?

Also, could you provide platform details?

**Comment by guillermooo** [comment]
@rhelsing I'm closing this issue, but please reopen if the problem persists.
