### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Mattiaslndstrm** [guillermooo/Six#210]
I see that you have an item on your todo-list that says documentation. I just wanted to add that it would be great with an exhaustive list of every command that Six can do. It would also be great if it was updated regularly and all new features to be marked as new. The reason I would like this is that I'm mostly memorizing the commands that's are available in Six and I have quite a backlog due to all the new features that you've been implementing the last few months, without a good way of finding what I don't know.

**Comment by guillermooo** [comment]
I am working on a script that will collect all the registered Six commands and output them in a suitable format for documenting. Keeping the previous version around (or all versions) will give a history of commands by Six version and a diff between two given versions.

**Comment by guillermooo** [comment]
@Mattiaslndstrm Unpublished yet, but it's being written here: https://github.com/SublimeSix/documentation

To see it now:

0. Check out repository and submodules
1. Install hugo
2. cd path/to/documentation
3. hugo serve -D
4. Go to URL printed by hugo

**Comment by guillermooo** [comment]
Docs are now available at http://docs.sublimesix.com.
