### ISSUE TITLE
Forcing case insensitive search no longer working

### ISSUE THREAD

**Issue by craig-cogdill** [guillermooo/Six#211]
I have been using the following in the Six.sublime-settings file for a few months without issue:
```
{
   "enable_ignore_case": true
}
```
A recent update sometime either early last week or late the week before seems to have broken this functionality, as all my searching is case sensitive now.

For reference, I also have `"enable_smart_case": false`

**Comment by guillermooo** [comment]
@craig-cogdill Odd. I've just run a quick test and it seems to work for me:

![image](https://user-images.githubusercontent.com/684948/41859534-a8c340ae-789c-11e8-96d1-0a411f1090cb.png)

I will check on more platforms and add a test case to see if there's something wrong.

**Comment by craig-cogdill** [comment]
@guillermooo That is odd. Am I editing the right file? The full path to that settings file is `~/Library/Application Support/Sublime Text 3/Packages/Six/Six.sublime-settings`

**Comment by guillermooo** [comment]
@craig-cogdill That file will be overwritten with every update to Six. Use the command palette (Ctrl+Shift+P on Windows, Cmd+Shift+P on macOS) and select "Preferences: Six Settings". That command should open the package and the user settings file side by side. You have to edit the user file for the changes to be persisted between Six updates.

**Comment by craig-cogdill** [comment]
That corrected the issue. Thanks!
