### ISSUE TITLE
Missing post repeat cursor behavior

### ISSUE THREAD

**Issue by burgreen** [guillermooo/Six#217]
Vintageous had a really nice behavior that I am seeking to enable.

After repeating the last command using ".", the cursor would stay in the starting column where the "." was initiated. This behavior allowed for some really quick and easy mods.

Can I enable Six to do this? If not, I would like to make a feature request.

**Comment by burgreen** [comment]
Eh, this does exactly what I want.
https://stackoverflow.com/questions/14567868/how-to-return-the-cursor-to-its-previous-position-after-the-dot-command/14568298

**Comment by guillermooo** [comment]
The backtick issue should be fixed in the next dev build.
