### ISSUE TITLE
Implement Change/Delete Inside/Around Item

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#22]
When I type ci" inside quotes in normal mode, expected behavior is to delete all the contents inside the quotes and enter insert mode inside.

**Comment by rhelsing** [comment]
@guillermooo is this implemented now?

**Comment by guillermooo** [comment]
Nope. My mistake. Reopening.

**Comment by guillermooo** [comment]
Wait. This is different to your other issue about ca" and friends. This one is actually done. Closing again. Let me know if I'm still utterly confused.

**Comment by guillermooo** [comment]
@rhelsing  BTW, you should be able to use ci", ci', ci`, ci(, ci[ and ci{.

**Comment by rhelsing** [comment]
thank you!
