### ISSUE TITLE
Six upgrade error - on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by artzte** [guillermooo/Six#220]
Any idea how to get past this? Rebooting does not help.

````
An error occurred while trying to finish the upgrade of Six. You will most likely need to restart your computer to complete the upgrade.

**Comment by guillermooo** [comment]
@artzte Could you please describe how you are updating Six and where do you see that message?

**Comment by artzte** [comment]
I just start Sublime. Usually the updates install automatically.

**Comment by guillermooo** [comment]
I suppose you see that message in the ST console? It looks like an issue with Package Control. Maybe reinstalling Six from scratch will help. Or resetting the ST Data directory.

https://www.sublimetext.com/docs/3/revert.html

Six does not have anything to do with any upgrade process, so I don't think it can fix this issue.
