### ISSUE TITLE
Add 'di<char>' mappings 

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#222]
I wanted to delete inside `[]` in my code so I ran `di[` but that did nothing.

Can you please add that action to Six?

Amongst other objects like `di{`, `di'`, 'di"' and perhaps more. Those are my most used ones though.

**Comment by guillermooo** [comment]
@nikitavoloboev I use those motions pretty often, and they all work in Six now. I don't have a mac handy at the moment, but I'll check as soon as I am back home in a few days.

**Comment by nikitavoloboev** [comment]
It was a mistake on my side. The bindings work well on macOS too.
