### ISSUE TITLE
Holding 'h', 'j', 'k', 'l' key does'nt move the cursor

### ISSUE THREAD

**Issue by thibaut-poullain** [guillermooo/Six#224]
Hi, 

I used Six before and that's a new behavior on a new mac setup. 
The cursor move once and stay in place. 
The arrow keys works fine.

That's realy anoying :P 

Thx for your help ! :)

The package in installed :

- A file icon
- Advanced new file
- AlignTab
- AllAutocomplete
- Autosave
- Clipboard manager
- Dashdoc
- GitGutter
- Material theme
- Pretty JSON
- SidebarEnhancements
- Six (of course ;)
- Lots of linters ;)

My sublime text settings :

> {
> 	"auto_complete": true,
> 	"auto_complete_commit_on_tab": true,
> 	"bold_folder_labels": true,
> 	"caret_style": "smooth",
> 	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
> 	"copy_with_empty_selection": true,
> 	"default_encoding": "UTF-8",
> 	"ensure_newline_at_eof_on_save": true,
> 	"find_selected_text": true,
> 	"font_face": "Operator Mono",
> 	"font_options":
> 	[
> 		"subpixel_antialias",
> 		"gray_antialias"
> 	],
> 	"font_size": 15,
> 	"highlight_line": false,
> 	"ignored_packages":
> 	[
> 		"C#",
> 		"C++",
> 		"Erlang",
> 		"Go",
> 		"Java",
> 		"LaTeX",
> 		"Matlab",
> 		"Objective-C",
> 		"OCaml",
> 		"Pascal",
> 		"Perl",
> 		"R",
> 		"Scala",
> 		"Vintage"
> 	],
> 	"indent_guide_options":["draw_normal","draw_active"],
> 	"index_files": true,
> 	"line_padding_bottom": 2,
> 	"line_padding_top": 3,
> 	"rulers":
> 	[80],
> 	"tab_size": 2,
> 	"theme": "Material-Theme.sublime-theme",
> 	"translate_tabs_to_spaces": true,
> 	"trim_trailing_white_space_on_save": true,
> 	"word_separators": "./\\()\"'-:,.;<>~@#$%^&*|+=[]{}`~",
> 	"word_wrap": true
> }

**Comment by guillermooo** [comment]
From the official Sublime Text docs:

> OS X Lion
> In Lion, holding down a key won't repeat it, but will instead show a popup menu to select between character variations. This doesn't work well with command mode, so you may want to disable it. This can be done via entering this at the terminal:
>
> `defaults write com.sublimetext.2 ApplePressAndHoldEnabled -bool false`

Let me know if that helps.
