### ISSUE TITLE
Lose focus on Sublime Text to previous app used when closing last tab of active window

### ISSUE THREAD

**Issue by nikitavoloboev** [guillermooo/Six#225]
I have these two bindings set up for Six:

```
 { "keys": [" ", "a"], "command": "six_press_key", "args": {"key": [":", "w", "q", "<CR>"], "is_interactive": false }, "context": [{ "key": "six_is_in_command_mode" }, {"key": "six_is_accepting_input", "operand": false }]},
  {
    "keys": [" ", "q"],
    "command": "close",
    "context": [{ "key": "six_is_in_command_mode" }]
  }
```

One issue I found with them is that often when I close the only tab in a window, it closes the window but also has focus still on Sublime Text. I very often search a file to edit with Alfred, edit the file and close it and want to instantly continue using the app I was using before then (my browser usually).

Is it possible to make Six lose focus from Sublime Text and give focus to the previous app user was using on these two bindings? Not sure how to add that.

Thank you.

**Comment by guillermooo** [comment]
I'll check this as soon as I have a mac handy again.

**Comment by guillermooo** [comment]
@nikitavoloboev Do you know of any way of using plain ST without Six where you get the desired behavior?

**Comment by nikitavoloboev** [comment]
@guillermooo I am not sure if one can do it with plain ST as I am not too familiar with what it can do. 

But on macOS, once you close the last tab in an open window. The window gets closed and Sublime Text will still be active (that is expected behavior).

What I wish though, if I close the last tab in the open window it would both close the tab and switch to 'last application' that was active. I feel like this is out of scope for Six plugin though so feel free to close the issue.

**Comment by guillermooo** [comment]
Yeah, I don't think Six can do that. I'll close the issue.

On Windows, you can keep pressing Alt+Esc to iterate through the previously active apps. I'm not sure whether a shortcut like that exists in macOS.
