### ISSUE TITLE
{Visual}{u,U} applies to entire line in visual mode

### ISSUE THREAD

**Issue by slice** [guillermooo/Six#228]
```js
Console.Log('Hello!')
```

with the cursor inside of `'hello!'`, running `vi'u` (which should only lowercase the contents of the string) lowercases the entire line and moves the cursor to the beginning of the line.

When running in vim, the cursor moves to the `h` after lowercasing.

`U` behaves similarly.

When using the motion instead of visual (`gui'` and `gUi'`), it works properly.

**Comment by guillermooo** [comment]
The commands regressed after implementing `gUU` and `guu`. Will be fixed by the next dev version.
