### ISSUE TITLE
Implement :wq

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#23]
I would expect `:wq` to save and close the current tab.

**Comment by rhelsing** [comment]
@guillermooo would love to help out.. would you consider making a quick write up (and post as wiki or other) explaining the organization of the codebase and prerequisites that need to be understood first?

**Comment by guillermooo** [comment]
Six isn't currently open source. It's hosted here only so that Package Control can find it. In the future it may be possible that parts of Six can be worked on externally, but I'm not sure if/when that will happen.

**Comment by rhelsing** [comment]
@guillermooo this seems to be almost working.. it works on an unchanged file when typing `:q`.. it also works on a modified buffer when typing `:wq`.. it currently doesn't close an unmodified buffer when pressing `:wq` - I generally use `:wq` to close out unmodified buffers out of habit and this works in vim.. thoughts?

**Comment by guillermooo** [comment]
Hm. I´ve just tried on Vim and it errors if I try to `:wq` a newly created, empy, buffer. It demands a file name.

**Comment by rhelsing** [comment]
@guillermooo yes you are right, I mean on a pre-existing file that has contents in the buffer but has not been modified.

```bash
$ cat Readme.md

Hello World

$ vim Readme.md

Hello World

:wq
$
```

**Comment by guillermooo** [comment]
OK, thanks, I´ll take a look!

**Comment by guillermooo** [comment]
Here's what I do:

- I open ST
- Using the command palette, I open a file
- I go `:wq` and the file closes

This works using Win 10 Pro. I think this is the desired behavior for your use case?

**Comment by rhelsing** [comment]
That is the desired behavior. I am on macOS Sierra. When I repeat those steps, the file does not close.

![q](https://cloud.githubusercontent.com/assets/392594/25863221/fb0de90a-34b8-11e7-9828-3bfe1f921628.gif)

**Comment by guillermooo** [comment]
I've just checked this on macOS Sierra and it's working for me too. Could it be an interaction with some  other package? Is the ST console showing any logs from Six?

**Comment by rhelsing** [comment]
@guillermooo It's working for me too now..
