### ISSUE TITLE
esc directly after O or o does not remove whitespace from autoindent

### ISSUE THREAD

**Issue by davea1** [guillermooo/Six#230]
Using `O` or `o` followed immediately by `esc` will leave behind whitespace in cases where an autoindent has occurred.

With Vim, all such whitespace is removed as soon as `esc` is hit, leaving only a blank line.

**Comment by guillermooo** [comment]
This seems to depend on the `autoindent` option. Vim options will be available in the future, but I have no immediate plans for them.

**Comment by davea1** [comment]
I think there is some confusion here. A new Vim option is not needed. This is how Sublime Six should behave currently with the default Sublime Text and Sublime Six options therefore this is a Vim compatibility issue and not an options issue.

By default Sublime Text has `auto_indent` and `smart_indent` enabled. Having them enabled is somewhat analogous to having the `autoindent` option enabled in Vim, which I typically do because I want this behavior.

The issue here is that when <kbd>O</kbd> or <kbd>o</kbd> is used to insert a line while auto-indentation is enabled, leading whitespace is added, as would be expected, so that any text that is subsequently entered is aligned properly. If <kbd>Esc</kbd> is then used immediately rather actually than typing any text, Vim is being helpful and senses that you probably just wanted to enter a blank line, therefore any whitespace is immediately removed leaving just a blank line as desired. This is actually a common method used within Vim for  adding blank lines. This feature also works as expected in Vim if you use something like <kbd>1</kbd><kbd>0</kbd><kbd>o</kbd><kbd>Esc</kbd>, which will leave you with 10 additional blank lines (no whitespace).

I do not want nor personally need additional Vim options to disable `autoindent` since I actually want auto-indentation. I just think that the behavior here when auto-indentation is enabled (the Sublime Text default) should mimic what happens in Vim.

Note - the Vim emulation extension available for VSCode behaves correctly in this respect as does the Vim emulation that is built into SlickEdit.

**Comment by guillermooo** [comment]
@davea1 Thanks for the clarification! I will look into this again.

**Comment by guillermooo** [comment]
OK, I see what you mean now. I'll try to fix this.

**Comment by guillermooo** [comment]
Should be partially fixed in the next dev build; there's a bug where undoing requires two steps.
