### ISSUE TITLE
dd not repeatable. 

### ISSUE THREAD

**Issue by burgreen** [guillermooo/Six#231]
Similar to #229, the `dd` command is not repeatable either.

**Comment by guillermooo** [comment]
`dd` seems to be repeatable for me.

After running the command, you should get this in the console:

```python
window.settings().get("vim")[":command:"]
["d", "d"]
```

**Comment by burgreen** [comment]
I appreciate your responsiveness. 

Just to clarify: if you type `dd` (which deletes the current line), and then type `.`, it deletes the next current, etc, deleting a line with each `.` typed?

**Comment by guillermooo** [comment]
Yes. The snippet shown above retrieves the command that the dot operator will repeat.

**Comment by guillermooo** [comment]
Closing this as it doesn't seem to be a general issue. Please reopen if you continue having trouble making this work.
