### ISSUE TITLE
"vat" doesn't properly find the closing tag

### ISSUE THREAD

**Issue by elpres** [guillermooo/Six#232]
With this bit of HTML:

```html
<div class="a">
    <div class="a"></div>
</div>
```

if you go to the first line and type `vat`, only the first two lines get selected. The problem seems to only occur though when there are attributes in the tag. Without the `class` attributes `vat` correctly selects all three lines.

**Comment by guillermooo** [comment]
Thanks for the report.

The implementation of `it`/`at` will be revised to be as close to Vim's as possible. At the moment it isn't a direct port of the C code.

**Comment by guillermooo** [comment]
Will be fixed in the next dev build.
