### ISSUE TITLE
Shortening large offscreen selections cause weird scrolling

### ISSUE THREAD

**Issue by slice** [guillermooo/Six#237]
If you enter visual line mode (`V`) then select a large amount of text (so that the selection cannot fit in the viewport without scrolling), shortening the selection will cause the view to scroll back to beginning to the selection, then back down to the end, repeating.

* `V`
* `}}}}}}}}` (select a large amount of text)
* `{{{{` (go back, will scroll weirdly)

**Comment by guillermooo** [comment]
Thanks for the report!

**Comment by guillermooo** [comment]
Will be fixed in the next dev build.
