### ISSUE TITLE
implement gk

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/Six#50]

**Comment by DrBones** [comment]
Hi,

I wonder, is there something I can do to speed up the implementation of this (and of course the respective "gj" issue) ? Or is there possibly a workaround I can apply on my end?
I write a lot of latex at the moment and rely a lot on wrapped lines and moving by real line is quite the inconvenience, although very vim like I believe :). This is basically what keeps me from switching from NeoVintageous, which eats my CPU/Battery with the remapped j -> gj keybinding unfortunately.

Thanks

**Comment by guillermooo** [comment]
To my knowledge, this can only be implemented with a workaround at the moment---ST does not offer a way of detecting line wrap boundaries in any way. I think the workaround should work ok in the general case, so I'll try to use that for now.

**Comment by guillermooo** [comment]
Implemented.
