### ISSUE TITLE
implement B

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/Six#56]

**Comment by Strangehill** [comment]
This isn't working right. <-- it should take only three W motions to get from the first character to 'right', but it takes four, because of an extra step at "isn't".

**Comment by guillermooo** [comment]
@Strangehill It may be that your examples got lost due to formatting? Could you please re-add them?

**Comment by Strangehill** [comment]
That wasn't too clear, sorry! The example sentence is: "This isn't working right."

**Comment by guillermooo** [comment]
Fixed.
