### ISSUE TITLE
implement 'ctrl-r' for redo

### ISSUE THREAD

**Issue by ev0rtex** [guillermooo/Six#87]
I can easily undo using 'u' but cannot seem to redo using ^r

**Comment by guillermooo** [comment]
I have to think what to do about CTRL- commands. Whether to let users enable all of them with a singlesetting or via several settings. This probably an issue primarily on Windows, where Ctrl+C and friends are very common shortcuts people tend to take for granted.

Also, Ctrl+R clobbers ST functionality, so it should be replaced somehow too within Six, I guess. Probably for Wave 2, although I'm missing it too...

**Comment by ev0rtex** [comment]
Just a thought..you could do something like:
```json
{
  "six_ctrl_keys": true
}
```
to enable all of them and then alternatively allow a list of specific overrides if desired:
```json
  "six_ctrl_keys": [ "r", "a", "x", "u", "d", "f", "b"]
}
```

**Comment by guillermooo** [comment]
Implemented. For completeness, the relevant option is `"enable_ctrl_keys": True`.
