### ISSUE TITLE
Backwards search with N

### ISSUE THREAD

**Issue by MSch** [guillermooo/Six#89]
I just did a clean reinstall of Sublime Text, this time switching from Vintageous to Six - trying to evaluate it.

It appears that while forward search with `n` works, backwards search with `Shift-n` doesn't.

**Comment by guillermooo** [comment]
That's correct. Backward search has to be implemented from scratch, as ST does not provide it via the API. I think this command is planned for Wave 2, which will start after a Code Quality Cycle which is starting soon.

I will try to fix some issues Vintageous has with this.
