### ISSUE TITLE
Document: Setting for instructing yank operations to propagate to system clipboard

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/Six#9]
Name: `use_system_clipboard_always`. In *Six.sublime-settings*.

**Comment by guillermooo** [comment]
Name: `use_system_clipboard`.

**Comment by guillermooo** [comment]
Document this.

**Comment by UnityJake** [comment]
Massive thanks - this is a great improvement. For me personally - this plus support for:
J
r
:<line>
Ctrl+f
Ctrl+b
%
zz

and I would find six complete for my VI usage

**Comment by guillermooo** [comment]
@UnityJake `:` should be working now, but only a handful of commands are available at the moment. The rest will probably be implemented during this iteration.
