### ISSUE TITLE
v0.1.30 breakage; plugin not working

### ISSUE THREAD

**Issue by jaytaylor** [guillermooo/Six#90]
Six is not working with ST3 + latest version:

```
Unknown key esc
Unable to parse binding {args: {key: <Esc>}, command: vim_press_key, context: [{key: vim_accept_any_input}], keys: [esc]}
```

**Comment by am6422** [comment]
Insert does replace avec using i key...

**Comment by guillermooo** [comment]
All tests are passing here. Have you tried restarting ST? Could you please provide platform details?

**Comment by jaytaylor** [comment]
Not sure what is meant by that.  Six was working fine, then I restarted ST3, and now it's not working anymore after auto updating to 0.1.30.

**Comment by guillermooo** [comment]
I'm primarily using Win10 and I have just installed 0.1.30 via Package Control and everything seems to be working fine. The test suite is also passing. Six is the only package I have installed, though.

**Comment by jaytaylor** [comment]
Also, to be clear, changing between command mode, insert mode, and visual mode works fine.

But actually trying to enter a command, for example:

````
:126<CR>
```

Doesn't work, the command pane never appears.

**Comment by jaytaylor** [comment]
Also, to be clear, changing between command mode, insert mode, and visual mode works fine.

But actually trying to enter a command, for example:

```
:126<CR>
```

Doesn't work, the command pane never appears.

**Comment by guillermooo** [comment]
Do you see any Six log lines in the ST console?

**Comment by jaytaylor** [comment]
I even tried removing all the "old" vintage* packages, still getting that `esc` error on boot and things aren't working.

Should I just go back to using Vintageous? *g*

**Comment by guillermooo** [comment]
BTW, there is not command line pane yet. Only a handful of command line commands work, and they show up in the status bar.

**Comment by jaytaylor** [comment]
The only six-related console messages I see are the "unknown key esc" which I provided when first filing this issue.

**Comment by jaytaylor** [comment]
Okay, well in any case the commands are definitely not working..

**Comment by guillermooo** [comment]
If there is no log line like this in the console:

```
2017-04-30 20:25:49,875 - Six.lib.command_state - ERROR - 'NoneType' object has no attribute 'reset'
```

then it's less likely that the error comes from Six.

The only command-line commands that work now are `:w` and `:q` if I remember correctly.

**Comment by guillermooo** [comment]
Ah, I now see the error you refer to, but it's not preventing Six from working for me. I'll take a closer look.

**Comment by guillermooo** [comment]
There was indeed a key with the wrong name in the Six key map. I'll push a fix for that momentarily.

**Comment by guillermooo** [comment]
@jaytaylor The latest version should fix the error log issue. Also, commands like the one you indicated are expected to not work at the moment, so I'm closing this issue now, but feel free to reopen if other issues persist.

**Comment by jaytaylor** [comment]
Alright, thanks for the quick followup and fix @guillermooo !

Cheers,
Jay
