### ISSUE TITLE
Fully Implement . (repeat command)

### ISSUE THREAD

**Issue by rhelsing** [guillermooo/Six#91]
I should be able to visually select a block of text, run Shift+> to indent once, but then I should be able to hit period (.) to repeat that command. There seems to be an issue with multi-step commands because this doesn't work on macros either.. only repeats a portion of the macro. This, along with :wq are the only huge things missing from my workflow currently..

Very impressed with how much progress you are making in such a short time

**Comment by guillermooo** [comment]
Repeating visual commands seems to be a tad more involved than I thought. Either I have not yet understood fully how Vim does it, or it's rather complicated. In short: repeating visual commands (and therefore using macros involving those commands) is missing intentionally.

Books on Vim seem to hint at the fact that advanced users of Vim should prefer normal mode over other modes (but I know old habits die hard!). In fact,  Six is being specifically built around repeatability (and macro recording) in normal mode. To be a bit dramatic, the command that will determine Six' success at its intended goals will be `:normal`, which, again, some people claim is superior to macros. What it certainly does, however, is require the internals of the editor to process keys in a repeatable and non-interactive way that exactly replicates interactive input. This is a good test for how capable the emulator is.

With that said, repeating visual commands will be possible in the future, but, honestly, I'm not spending too much time on researching this at the moment. When I'm done cleaning up a few loose ends from Wave 1, I might look into this. Maybe it isn't that complicated after all.

`:wq` should be easy to add even without full support for command line commands. I'll make a note to implement it soon.

Thanks for the encouragement! 👍

**Comment by guillermooo** [comment]
Actually, I found the documentation and it seems pretty simple. I don´t know why I though it was more complex.

**Comment by rhelsing** [comment]
@guillermooo that is great to hear! Thank you so much for the work you are doing!

**Comment by rhelsing** [comment]
@guillermooo any progress on this.. still the main case I am hoping for is the original one mentioned in this thread

**Comment by guillermooo** [comment]
This is planned for this iteration. I'll try to bump up the priority.

**Comment by guillermooo** [comment]
Implemented for visual and visual line mode when the selection is oriented forwards. I'll close this issue and open a new one for the rest of the cases.
